### ISSUE TITLE
[App Request]Media Player Classic Qute Theater

### ISSUE THREAD

**Issue by bsucker98** [community-repositories-for-solus/solus-community-repo#11]
could this be added here,

Name: Media Player Classic Qute Theater(mpc-qt)
Homepage: https://github.com/cmdrkotori/mpc-qt
**Note:** already has been requested here, https://dev.solus-project.com/T4979
                 seems they won't accept aymore third party apps

Requesting not to make it, just another media player. I've gone through lot of them, & even the best of them lags (VLC/mpv lot better), not that smooth when seeking & really poor playback quality for some formats(very noticable when I played the same in Windows)
finally, this got me covered.

THNX

**Comment by ThanosApostolou** [comment]
I've never managed to find people in order to maintain a repository as such together, that's why I haven't published it anywhere. Sadly, I'm not using Solus anymore so I cannot help. :/
